// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3CttfQszFhZjce9uUxaPyDCtunTMQ7XM',
    appId: '1:586614266550:web:5a70c9565c68cbd4f6a417',
    messagingSenderId: '586614266550',
    projectId: 'lostlink-2810f',
    authDomain: 'lostlink-2810f.firebaseapp.com',
    storageBucket: 'lostlink-2810f.firebasestorage.app',
    measurementId: 'G-GR06YYQW6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbk_5B4Voo_RlB4-KNX_mZyTq1mSKYSyE',
    appId: '1:586614266550:android:c2db02a03d45a83ef6a417',
    messagingSenderId: '586614266550',
    projectId: 'lostlink-2810f',
    storageBucket: 'lostlink-2810f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByODyNid6r8PBghHykGNjr90jAqOIdN08',
    appId: '1:586614266550:ios:ba688478b2555281f6a417',
    messagingSenderId: '586614266550',
    projectId: 'lostlink-2810f',
    storageBucket: 'lostlink-2810f.firebasestorage.app',
    iosBundleId: 'com.example.lostlink',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByODyNid6r8PBghHykGNjr90jAqOIdN08',
    appId: '1:586614266550:ios:ba688478b2555281f6a417',
    messagingSenderId: '586614266550',
    projectId: 'lostlink-2810f',
    storageBucket: 'lostlink-2810f.firebasestorage.app',
    iosBundleId: 'com.example.lostlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3CttfQszFhZjce9uUxaPyDCtunTMQ7XM',
    appId: '1:586614266550:web:409ffc772b945c69f6a417',
    messagingSenderId: '586614266550',
    projectId: 'lostlink-2810f',
    authDomain: 'lostlink-2810f.firebaseapp.com',
    storageBucket: 'lostlink-2810f.firebasestorage.app',
    measurementId: 'G-YH9NSKHY3Q',
  );
}
